android: don't crash when callback not registered
bkonyi/FlutterGeofencing pull request #36
Opened 2020-01-18 20:07 UTC by accek

It happens sometimes that when an app is uninstalled and reinstalled,
or app data is cleared, that the geofencing framework calls our service
and the callback is not registered yet, causing a crash.

2020-01-20 00:25 UTC, bkonyi commented
I can't seem to remember if 0 is actually a valid raw callback handle or not, but I don't think we try and restrict it since there's no reason the hashing algorithm used to create the handle can't output 0. Can you share where the crash is happening exactly? This code should already bail out if a callback handle isn't valid.

2020-01-20 13:17 UTC, accek commented
Well, maybe I'm misinterpreting the stack trace or the code. Here it is:

```
Fatal Exception: java.lang.RuntimeException
Unable to create service io.flutter.plugins.geofencing.GeofencingService: java.lang.IllegalStateException: FlutterCallbackInformati…formation(callbackHandle) must not be null
Fatal Exception: java.lang.RuntimeException: Unable to create service io.flutter.plugins.geofencing.GeofencingService: java.lang.IllegalStateException: FlutterCallbackInformati…formation(callbackHandle) must not be null
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3965)
       at android.app.ActivityThread.access$1500(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by java.lang.IllegalStateException
FlutterCallbackInformati…formation(callbackHandle) must not be null
Caused by java.lang.IllegalStateException: FlutterCallbackInformati…formation(callbackHandle) must not be null
       at io.flutter.plugins.geofencing.GeofencingService.startGeofencingService(GeofencingService.kt:65)
       at io.flutter.plugins.geofencing.GeofencingService.onCreate(GeofencingService.kt:114)
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:3953)
       at android.app.ActivityThread.access$1500(ActivityThread.java:219)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1875)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

2020-04-22 12:27 UTC, ertgl requested changes
Hello. May vary depending on the version but, `callbackHandle ==`**`0L`** can prevent errors such `Operator == cannot be applied to 'Long' and 'Int'`.

2020-08-12 08:49 UTC, JFreakDK commented
I did not see your fix before I created one myself. I reported it here: #60 and tried to catch the exception #62 instead of your approach.

What is the status here @bkonyi ? Can we include on of the fixes?

2020-10-28 17:49 UTC, bkonyi commented
This appears to have already been fixed on master. Sorry for the delay on this!

2020-10-28 17:49 UTC, closed without merging